### ISSUE TITLE
script no longer works with latest King Soopers or Kroger coupons

### ISSUE THREAD

**Issue by a1ch3mist** [rwerthman/ks_coupon_clicker#1]
Script is broken with current website. Do you have a workaround or can you please update?

**Comment by rwerthman** [comment]
Thanks for notifying me! I haven't used it in a while but let me see if I can get it to work again.

**Comment by rwerthman** [comment]
Hey @a1ch3mist, it is working now can you retest?  Kroger limits you to 150 coupons...I thought this was a larger number.

I will open some more issue for new features like

1. telling the user how many coupons it found #2
2. loading all of the coupons instead of the user having to scroll to the bottom of the page #5
3. telling the user when it is completed #3 
4. Stopping the script when the limit is reached #3 

Finally, need to get this in the extension store so people can install it without having to be in developer mode #4.
